name: "Close stale issues"
on:
  workflow_dispatch:
    branches:
    - main
     
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 90
        days-before-close: 0
        stale-issue-message: 'This issue is being closed as stale'
        close-issue-message: 'Doing some cleanup/spring cleaning and closing all issues older than 90 days. Please reopen if issue is still relevant.'
